### ISSUE TITLE
duplicated-property-value-in-media - avoid 'false' error when both short and long notations are used

### ISSUE THREAD

**Issue by IgnatovDan** [IgnatovDan/stylelint-bem-newbie#57]
For example, `Unexpected 'margin: 0' in '@media ...' duplicates with '.header'` error occurs for this config:

```css
.header {
    margin: 0;
}

@media screen and (max-width: 800px) {
     .header {
        margin-top: 30px;
    }
}

@media screen and (max-width: 400px) {
    .header {
         margin: 0;
    }
}
```
