### ISSUE TITLE
Show error if there are several media for one size

### ISSUE THREAD

**Issue by IgnatovDan** [IgnatovDan/stylelint-bem-newbie#58]
For example:
```css
@media screen and (min-width: 768px) {
    .header {
        padding: 90px;
    }
}

@media screen and (min-width: 768px) {
    .header {
        display: flex;
        padding: 0 24px 73px;
    }
}
```
